module.exports = {
    FOOTPRINT: '_footPrint',
    DECORATED: 'isDecorated',
    TYPE: 'typeDecoratorApplied',
    DECORATED_VALUE: 'decoratedValue',
    ORIGIN_VALUE: 'originValue',
    DEFAULT_ARGS: 'defaultArgs',
    PARAM: 'methodParamsType',
    REGEX_WHITE_SPACE: /\s/g,
    REGEX_PARAM_SEPERATOR: /\s*\,\s*/g,
    //REGEX_DECORATOR_DETECT: /@.*/g,
    REGEX_DECORATOR_DETECT: /(\s|\n)*@.*(\s|\n)*/g,
    //REGEX_FUNCTION_DETECT: /^function(\s+\w*)*\s*\((.*)\)/,
    REGEX_FUNCTION_DETECT: /^function(\s+\w*)*\s*\(((.|\n)*)\)/,
    REGEX_FUNCTION_BODY_DETECT: /{(.|\n)*}/,
    REGEX_ASIGNMENT_EXPRESSION_RHS: /(\s|\n)*=(\s|\n)*\w+(\s|\n)*/g,
    REGEX_DEFAULT_ARG: this.REGEX_ASIGNMENT_EXPRESSION_RHS,
    REGEX_ES6_CLASS_DETECT: /^class/,
    REGEX_ES6_CONSTRUCTOR_DETECT: /constructor\s*\((.*)\)/,
}